///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest3Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("18db4a00-a9c3-483e-96a6-a88240cb3bac")]
    public partial class MyTest3Repository : RepoGenBaseFolder
    {
        static MyTest3Repository instance = new MyTest3Repository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTest3Repository element repository.
        /// </summary>
        [RepositoryFolder("18db4a00-a9c3-483e-96a6-a88240cb3bac")]
        public static MyTest3Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest3Repository() 
            : base("MyTest3Repository", "/", null, 0, false, "18db4a00-a9c3-483e-96a6-a88240cb3bac", ".\\RepositoryImages\\MyTest3Repository18db4a00.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("18db4a00-a9c3-483e-96a6-a88240cb3bac")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest3RepositoryFolders
    {
    }
#pragma warning restore 0436
}
