///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CloseBrowser recording.
    /// </summary>
    [TestModule("d5f0b5b5-f403-4e8a-a2cb-af463bdc181f", ModuleType.Recording, 1)]
    public partial class CloseBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoRepository repository.
        /// </summary>
        public static DemoRepository repo = DemoRepository.Instance;

        static CloseBrowser instance = new CloseBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CloseBrowser()
        {
            NewVariable = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CloseBrowser Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("23132a51-0055-463a-beb9-23a872a37bbf")]
        public string NewVariable
        {
            get { return repo.NewVariable; }
            set { repo.NewVariable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Id' from item 'LoansPQXpressAccountsLogin.Editbox_Question1' and assigning its value to variable 'NewVariable'.", repo.LoansPQXpressAccountsLogin.Editbox_Question1Info, new RecordItemIndex(0));
            NewVariable = repo.LoansPQXpressAccountsLogin.Editbox_Question1.Element.GetAttributeValueText("Id");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'LoansPQXpressAccountsLogin'.", repo.LoansPQXpressAccountsLogin.SelfInfo, new RecordItemIndex(1));
            Host.Current.CloseApplication(repo.LoansPQXpressAccountsLogin.Self, new Duration(0));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fhsdh'.", new RecordItemIndex(2));
            Keyboard.Press("fhsdh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "sdafasf", new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (asfasf='asfsaf') on item 'LoansPQXpressAccountsLogin.Button_Continue'.", repo.LoansPQXpressAccountsLogin.Button_ContinueInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.LoansPQXpressAccountsLogin.Button_ContinueInfo, "asfasf", "asfsaf");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoansPQXpressAccountsLogin.Button_Login' at Center.", repo.LoansPQXpressAccountsLogin.Button_LoginInfo, new RecordItemIndex(5));
            repo.LoansPQXpressAccountsLogin.Button_Login.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
