///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("1bb099e4-5eb9-4130-84cd-2ad7c4afe3d7")]
    public partial class DemoRepository : RepoGenBaseFolder
    {
        static DemoRepository instance = new DemoRepository();
        DemoRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        DemoRepositoryFolders.LoansPQXpressAccountsLoginAppFolder _loanspqxpressaccountslogin;
        DemoRepositoryFolders.Window_ChooseFileToUploadAppFolder _window_choosefiletoupload;
        DemoRepositoryFolders.MessageFromWebpageAppFolder _messagefromwebpage;
        DemoRepositoryFolders.DocumentSupportRequestInternetExplAppFolder _documentsupportrequestinternetexpl;

        /// <summary>
        /// Gets the singleton class instance representing the DemoRepository element repository.
        /// </summary>
        [RepositoryFolder("1bb099e4-5eb9-4130-84cd-2ad7c4afe3d7")]
        public static DemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DemoRepository() 
            : base("DemoRepository", "/", null, 0, false, "1bb099e4-5eb9-4130-84cd-2ad7c4afe3d7", ".\\RepositoryImages\\DemoRepository1bb099e4.rximgres")
        {
            _applicationundertest = new DemoRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _loanspqxpressaccountslogin = new DemoRepositoryFolders.LoansPQXpressAccountsLoginAppFolder(this);
            _window_choosefiletoupload = new DemoRepositoryFolders.Window_ChooseFileToUploadAppFolder(this);
            _messagefromwebpage = new DemoRepositoryFolders.MessageFromWebpageAppFolder(this);
            _documentsupportrequestinternetexpl = new DemoRepositoryFolders.DocumentSupportRequestInternetExplAppFolder(this);
        }

#region Variables

        string _NewVariable = "";

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("2087e133-8bfb-4280-8840-9c4f43a9c7de")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1bb099e4-5eb9-4130-84cd-2ad7c4afe3d7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("38df592c-ad85-4bf0-a3c1-fab2be9beebc")]
        public virtual DemoRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The LoansPQXpressAccountsLogin folder.
        /// </summary>
        [RepositoryFolder("541bdfc7-8392-4aff-866f-8a9527ababe5")]
        public virtual DemoRepositoryFolders.LoansPQXpressAccountsLoginAppFolder LoansPQXpressAccountsLogin
        {
            get { return _loanspqxpressaccountslogin; }
        }

        /// <summary>
        /// The Window_ChooseFileToUpload folder.
        /// </summary>
        [RepositoryFolder("83e0c404-aa31-4728-8c58-47bfb460ce60")]
        public virtual DemoRepositoryFolders.Window_ChooseFileToUploadAppFolder Window_ChooseFileToUpload
        {
            get { return _window_choosefiletoupload; }
        }

        /// <summary>
        /// The MessageFromWebpage folder.
        /// </summary>
        [RepositoryFolder("a5d1fad4-2c47-4ad2-8b4d-304eb67d49aa")]
        public virtual DemoRepositoryFolders.MessageFromWebpageAppFolder MessageFromWebpage
        {
            get { return _messagefromwebpage; }
        }

        /// <summary>
        /// The DocumentSupportRequestInternetExpl folder.
        /// </summary>
        [RepositoryFolder("d02b9c9c-b226-4ae5-b0e6-b4b04504e18d")]
        public virtual DemoRepositoryFolders.DocumentSupportRequestInternetExplAppFolder DocumentSupportRequestInternetExpl
        {
            get { return _documentsupportrequestinternetexpl; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DemoRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("38df592c-ad85-4bf0-a3c1-fab2be9beebc")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "38df592c-ad85-4bf0-a3c1-fab2be9beebc", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("38df592c-ad85-4bf0-a3c1-fab2be9beebc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("38df592c-ad85-4bf0-a3c1-fab2be9beebc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The LoansPQXpressAccountsLoginAppFolder folder.
        /// </summary>
        [RepositoryFolder("541bdfc7-8392-4aff-866f-8a9527ababe5")]
        public partial class LoansPQXpressAccountsLoginAppFolder : RepoGenBaseFolder
        {
            DemoRepositoryFolders.AspnetFormFolder _aspnetform;
            DemoRepositoryFolders.VehicleFormFolder _vehicleform;
            RepoItemInfo _img_homepagelogoInfo;
            RepoItemInfo _editbox_loginInfo;
            RepoItemInfo _button_loginInfo;
            RepoItemInfo _editbox_question1Info;
            RepoItemInfo _editbox_question2Info;
            RepoItemInfo _button_continueInfo;
            RepoItemInfo _select_officialfamilyuseInfo;
            RepoItemInfo _radiobutton_indirectloanInfo;
            RepoItemInfo _button_lettersanddocsInfo;
            RepoItemInfo _button_rquestdocsupportInfo;
            RepoItemInfo _title_documentsupportrequestInfo;
            RepoItemInfo _button_submitrequestInfo;
            RepoItemInfo _editbox_descriptionoldInfo;
            RepoItemInfo _editbox_documentnameInfo;
            RepoItemInfo _editbox_browseInfo;
            RepoItemInfo _select_requesttypeInfo;

            /// <summary>
            /// Creates a new LoansPQXpressAccountsLogin  folder.
            /// </summary>
            public LoansPQXpressAccountsLoginAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoansPQXpressAccountsLogin", "/dom[@domain='beta.loanspq.com']", parentFolder, 30000, null, false, "541bdfc7-8392-4aff-866f-8a9527ababe5", "")
            {
                _aspnetform = new DemoRepositoryFolders.AspnetFormFolder(this);
                _vehicleform = new DemoRepositoryFolders.VehicleFormFolder(this);
                _img_homepagelogoInfo = new RepoItemInfo(this, "Img_HomepageLogo", ".//form[#'aspnetForm']/center/table[1]//img[@src='https://beta.loanspq.com/images/logo_frontpage.gif']", 30000, null, "55bfa309-992f-4489-9c40-c2979a9cdb72");
                _editbox_loginInfo = new RepoItemInfo(this, "Editbox_Login", ".//form[#'aspnetForm']/center/table[2]/tbody/tr[2]/?/?/table//input[@name='ctl00$bc$LoginMain$txtLogin']", 30000, null, "dd81b37f-8fb0-4713-83fa-4f5e6719b029");
                _button_loginInfo = new RepoItemInfo(this, "Button_Login", ".//form[#'aspnetForm']/center/table[2]/tbody/tr[2]/?/?/table//input[@name='ctl00$bc$LoginMain$btnLogin']", 30000, null, "04319099-a0b6-4aad-bcd0-d80ec1fc226a");
                _editbox_question1Info = new RepoItemInfo(this, "Editbox_Question1", ".//form[#'aspnetForm']/center/table[2]/tbody/tr[2]/?/?/table/tbody/tr[2]/?/?/table//input[@name='ctl00$bc$MFLQuestions$Answer1']", 30000, null, "334f253d-b3c9-437a-a0ff-51cc49cd2afc");
                _editbox_question2Info = new RepoItemInfo(this, "Editbox_Question2", ".//form[#'aspnetForm']/center/table[2]/tbody/tr[2]/?/?/table/tbody/tr[2]/?/?/table//input[@name='ctl00$bc$MFLQuestions$Answer2']", 30000, null, "71d9d3e3-1141-413c-9d34-6f8bef86fa03");
                _button_continueInfo = new RepoItemInfo(this, "Button_Continue", ".//form[#'aspnetForm']/center/table[2]/tbody/tr[2]/td/table//td[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ Do\\ you\\ want\\ us\\ ']/?/?/input[@name='ctl00$bc$MFLQuestions$btnContinue']", 30000, null, "7955ad2f-2be2-4c98-9773-8125194a83e4");
                _select_officialfamilyuseInfo = new RepoItemInfo(this, "Select_OfficialFamilyUse", ".//select[#'ou_EmployeeOfLenderType']", 30000, null, "00b22bfd-973b-4550-bb4d-e363e75de0b6");
                _radiobutton_indirectloanInfo = new RepoItemInfo(this, "RadioButton_IndirectLoan", ".//span[#'IsIndirectLoan']/input[@type='radio' and @value='N']", 30000, null, "f7f87c7f-dae7-4af4-9d96-7b4f3981d7cf");
                _button_lettersanddocsInfo = new RepoItemInfo(this, "Button_LettersAndDocs", ".//a[#'pre_lab_lbtnLetters']", 30000, null, "a8e3f334-57fb-4c02-9228-6ced25d54ada");
                _button_rquestdocsupportInfo = new RepoItemInfo(this, "Button_RquestDocSupport", ".//div[#'pnlBody']/?/?/input[@name='PDFs$ctl01$button']", 30000, null, "9d54fc0d-2375-40eb-aadc-5cbf413a4529");
                _title_documentsupportrequestInfo = new RepoItemInfo(this, "Title_DocumentSupportRequest", ".//div[#'pageTitle']", 30000, null, "19ccbc6e-5ad5-43c2-a8aa-3cddd0238d31");
                _button_submitrequestInfo = new RepoItemInfo(this, "Button_SubmitRequest", ".//div[#'buttons']/input[@name='ctl00$Buttons$btnSubmit']", 30000, null, "f5c8f7bf-79cf-471f-b579-26981808ab14");
                _editbox_descriptionoldInfo = new RepoItemInfo(this, "Editbox_Descriptionold", ".//div[#'content']/?/?/table/tbody/tr[6]/?/?/textarea[@required='False']", 30000, null, "dd5aa331-9204-4248-8110-f4f5ee6044d8");
                _editbox_documentnameInfo = new RepoItemInfo(this, "Editbox_DocumentName", ".//div[#'content']/?/?/table/tbody/tr[6]/?/?/input[@name='ctl00$bc$NewName']", 30000, null, "3a4a5dad-196c-4bab-a26e-73bd1eea54c8");
                _editbox_browseInfo = new RepoItemInfo(this, "Editbox_Browse", ".//div[#'content']/?/?/table/tbody/tr[14]/?/?/input[@name='ctl00$bc$Attachment1']", 30000, null, "20aef02e-0503-4e28-8508-9e29a33c975f");
                _select_requesttypeInfo = new RepoItemInfo(this, "Select_RequestType", ".//div[#'content']/?/?/table/tbody/tr[1]/?/?/select[@name='ctl00$bc$RequestType']", 30000, null, "c305f423-3c97-41fb-b111-213e082914a3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("541bdfc7-8392-4aff-866f-8a9527ababe5")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("541bdfc7-8392-4aff-866f-8a9527ababe5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Img_HomepageLogo item.
            /// </summary>
            [RepositoryItem("55bfa309-992f-4489-9c40-c2979a9cdb72")]
            public virtual Ranorex.ImgTag Img_HomepageLogo
            {
                get
                {
                    return _img_homepagelogoInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Img_HomepageLogo item info.
            /// </summary>
            [RepositoryItemInfo("55bfa309-992f-4489-9c40-c2979a9cdb72")]
            public virtual RepoItemInfo Img_HomepageLogoInfo
            {
                get
                {
                    return _img_homepagelogoInfo;
                }
            }

            /// <summary>
            /// The Editbox_Login item.
            /// </summary>
            [RepositoryItem("dd81b37f-8fb0-4713-83fa-4f5e6719b029")]
            public virtual Ranorex.InputTag Editbox_Login
            {
                get
                {
                    return _editbox_loginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_Login item info.
            /// </summary>
            [RepositoryItemInfo("dd81b37f-8fb0-4713-83fa-4f5e6719b029")]
            public virtual RepoItemInfo Editbox_LoginInfo
            {
                get
                {
                    return _editbox_loginInfo;
                }
            }

            /// <summary>
            /// The Button_Login item.
            /// </summary>
            [RepositoryItem("04319099-a0b6-4aad-bcd0-d80ec1fc226a")]
            public virtual Ranorex.InputTag Button_Login
            {
                get
                {
                    return _button_loginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Button_Login item info.
            /// </summary>
            [RepositoryItemInfo("04319099-a0b6-4aad-bcd0-d80ec1fc226a")]
            public virtual RepoItemInfo Button_LoginInfo
            {
                get
                {
                    return _button_loginInfo;
                }
            }

            /// <summary>
            /// The Editbox_Question1 item.
            /// </summary>
            [RepositoryItem("334f253d-b3c9-437a-a0ff-51cc49cd2afc")]
            public virtual Ranorex.InputTag Editbox_Question1
            {
                get
                {
                    return _editbox_question1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_Question1 item info.
            /// </summary>
            [RepositoryItemInfo("334f253d-b3c9-437a-a0ff-51cc49cd2afc")]
            public virtual RepoItemInfo Editbox_Question1Info
            {
                get
                {
                    return _editbox_question1Info;
                }
            }

            /// <summary>
            /// The Editbox_Question2 item.
            /// </summary>
            [RepositoryItem("71d9d3e3-1141-413c-9d34-6f8bef86fa03")]
            public virtual Ranorex.InputTag Editbox_Question2
            {
                get
                {
                    return _editbox_question2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_Question2 item info.
            /// </summary>
            [RepositoryItemInfo("71d9d3e3-1141-413c-9d34-6f8bef86fa03")]
            public virtual RepoItemInfo Editbox_Question2Info
            {
                get
                {
                    return _editbox_question2Info;
                }
            }

            /// <summary>
            /// The Button_Continue item.
            /// </summary>
            [RepositoryItem("7955ad2f-2be2-4c98-9773-8125194a83e4")]
            public virtual Ranorex.InputTag Button_Continue
            {
                get
                {
                    return _button_continueInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Button_Continue item info.
            /// </summary>
            [RepositoryItemInfo("7955ad2f-2be2-4c98-9773-8125194a83e4")]
            public virtual RepoItemInfo Button_ContinueInfo
            {
                get
                {
                    return _button_continueInfo;
                }
            }

            /// <summary>
            /// The Select_OfficialFamilyUse item.
            /// </summary>
            [RepositoryItem("00b22bfd-973b-4550-bb4d-e363e75de0b6")]
            public virtual Ranorex.SelectTag Select_OfficialFamilyUse
            {
                get
                {
                    return _select_officialfamilyuseInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Select_OfficialFamilyUse item info.
            /// </summary>
            [RepositoryItemInfo("00b22bfd-973b-4550-bb4d-e363e75de0b6")]
            public virtual RepoItemInfo Select_OfficialFamilyUseInfo
            {
                get
                {
                    return _select_officialfamilyuseInfo;
                }
            }

            /// <summary>
            /// The RadioButton_IndirectLoan item.
            /// </summary>
            [RepositoryItem("f7f87c7f-dae7-4af4-9d96-7b4f3981d7cf")]
            public virtual Ranorex.InputTag RadioButton_IndirectLoan
            {
                get
                {
                    return _radiobutton_indirectloanInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RadioButton_IndirectLoan item info.
            /// </summary>
            [RepositoryItemInfo("f7f87c7f-dae7-4af4-9d96-7b4f3981d7cf")]
            public virtual RepoItemInfo RadioButton_IndirectLoanInfo
            {
                get
                {
                    return _radiobutton_indirectloanInfo;
                }
            }

            /// <summary>
            /// The Button_LettersAndDocs item.
            /// </summary>
            [RepositoryItem("a8e3f334-57fb-4c02-9228-6ced25d54ada")]
            public virtual Ranorex.ATag Button_LettersAndDocs
            {
                get
                {
                    return _button_lettersanddocsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Button_LettersAndDocs item info.
            /// </summary>
            [RepositoryItemInfo("a8e3f334-57fb-4c02-9228-6ced25d54ada")]
            public virtual RepoItemInfo Button_LettersAndDocsInfo
            {
                get
                {
                    return _button_lettersanddocsInfo;
                }
            }

            /// <summary>
            /// The Button_RquestDocSupport item.
            /// </summary>
            [RepositoryItem("9d54fc0d-2375-40eb-aadc-5cbf413a4529")]
            public virtual Ranorex.InputTag Button_RquestDocSupport
            {
                get
                {
                    return _button_rquestdocsupportInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Button_RquestDocSupport item info.
            /// </summary>
            [RepositoryItemInfo("9d54fc0d-2375-40eb-aadc-5cbf413a4529")]
            public virtual RepoItemInfo Button_RquestDocSupportInfo
            {
                get
                {
                    return _button_rquestdocsupportInfo;
                }
            }

            /// <summary>
            /// The Title_DocumentSupportRequest item.
            /// </summary>
            [RepositoryItem("19ccbc6e-5ad5-43c2-a8aa-3cddd0238d31")]
            public virtual Ranorex.DivTag Title_DocumentSupportRequest
            {
                get
                {
                    return _title_documentsupportrequestInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Title_DocumentSupportRequest item info.
            /// </summary>
            [RepositoryItemInfo("19ccbc6e-5ad5-43c2-a8aa-3cddd0238d31")]
            public virtual RepoItemInfo Title_DocumentSupportRequestInfo
            {
                get
                {
                    return _title_documentsupportrequestInfo;
                }
            }

            /// <summary>
            /// The Button_SubmitRequest item.
            /// </summary>
            [RepositoryItem("f5c8f7bf-79cf-471f-b579-26981808ab14")]
            public virtual Ranorex.InputTag Button_SubmitRequest
            {
                get
                {
                    return _button_submitrequestInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Button_SubmitRequest item info.
            /// </summary>
            [RepositoryItemInfo("f5c8f7bf-79cf-471f-b579-26981808ab14")]
            public virtual RepoItemInfo Button_SubmitRequestInfo
            {
                get
                {
                    return _button_submitrequestInfo;
                }
            }

            /// <summary>
            /// The Editbox_Descriptionold item.
            /// </summary>
            [RepositoryItem("dd5aa331-9204-4248-8110-f4f5ee6044d8")]
            public virtual Ranorex.TextAreaTag Editbox_Descriptionold
            {
                get
                {
                    return _editbox_descriptionoldInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_Descriptionold item info.
            /// </summary>
            [RepositoryItemInfo("dd5aa331-9204-4248-8110-f4f5ee6044d8")]
            public virtual RepoItemInfo Editbox_DescriptionoldInfo
            {
                get
                {
                    return _editbox_descriptionoldInfo;
                }
            }

            /// <summary>
            /// The Editbox_DocumentName item.
            /// </summary>
            [RepositoryItem("3a4a5dad-196c-4bab-a26e-73bd1eea54c8")]
            public virtual Ranorex.InputTag Editbox_DocumentName
            {
                get
                {
                    return _editbox_documentnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_DocumentName item info.
            /// </summary>
            [RepositoryItemInfo("3a4a5dad-196c-4bab-a26e-73bd1eea54c8")]
            public virtual RepoItemInfo Editbox_DocumentNameInfo
            {
                get
                {
                    return _editbox_documentnameInfo;
                }
            }

            /// <summary>
            /// The Editbox_Browse item.
            /// </summary>
            [RepositoryItem("20aef02e-0503-4e28-8508-9e29a33c975f")]
            public virtual Ranorex.InputTag Editbox_Browse
            {
                get
                {
                    return _editbox_browseInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_Browse item info.
            /// </summary>
            [RepositoryItemInfo("20aef02e-0503-4e28-8508-9e29a33c975f")]
            public virtual RepoItemInfo Editbox_BrowseInfo
            {
                get
                {
                    return _editbox_browseInfo;
                }
            }

            /// <summary>
            /// The Select_RequestType item.
            /// </summary>
            [RepositoryItem("c305f423-3c97-41fb-b111-213e082914a3")]
            public virtual Ranorex.SelectTag Select_RequestType
            {
                get
                {
                    return _select_requesttypeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Select_RequestType item info.
            /// </summary>
            [RepositoryItemInfo("c305f423-3c97-41fb-b111-213e082914a3")]
            public virtual RepoItemInfo Select_RequestTypeInfo
            {
                get
                {
                    return _select_requesttypeInfo;
                }
            }

            /// <summary>
            /// The AspnetForm folder.
            /// </summary>
            [RepositoryFolder("07de2267-1342-40f9-971f-366693965382")]
            public virtual DemoRepositoryFolders.AspnetFormFolder AspnetForm
            {
                get { return _aspnetform; }
            }

            /// <summary>
            /// The VehicleForm folder.
            /// </summary>
            [RepositoryFolder("c0ec1c1e-36dd-4e04-bfd8-67c7352ac018")]
            public virtual DemoRepositoryFolders.VehicleFormFolder VehicleForm
            {
                get { return _vehicleform; }
            }
        }

        /// <summary>
        /// The AspnetFormFolder folder.
        /// </summary>
        [RepositoryFolder("07de2267-1342-40f9-971f-366693965382")]
        public partial class AspnetFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _label_newappInfo;
            RepoItemInfo _listitem_vehicleInfo;
            RepoItemInfo _editbox_passwordInfo;
            RepoItemInfo _button_signinInfo;
            RepoItemInfo _label_invalidloginInfo;

            /// <summary>
            /// Creates a new AspnetForm  folder.
            /// </summary>
            public AspnetFormFolder(RepoGenBaseFolder parentFolder) :
                    base("AspnetForm", ".//form[#'aspnetForm']", parentFolder, 30000, null, false, "07de2267-1342-40f9-971f-366693965382", "")
            {
                _label_newappInfo = new RepoItemInfo(this, "Label_NewApp", "?/?/ul/?/?/img[@alt='New App']", 30000, null, "8b92ef18-cc48-4f08-8537-092cfcd6fc12");
                _listitem_vehicleInfo = new RepoItemInfo(this, "ListItem_Vehicle", "?/?/ul/?/?/ul/?/?/a[@innertext=' Vehicle  ']", 30000, null, "bc08fba5-85ac-4b90-b1ad-e0be997bd8c8");
                _editbox_passwordInfo = new RepoItemInfo(this, "Editbox_Password", "center/table[2]/tbody/tr[2]/?/?/table/tbody/tr[3]/?/?/table//input[@name='ctl00$bc$MFLPasswordPrompt$Password']", 30000, null, "f704986e-abbb-4379-8fc3-56d5f4a1067f");
                _button_signinInfo = new RepoItemInfo(this, "Button_SignIn", "center/table[2]/tbody/tr[2]/?/?/table/tbody/tr[3]/?/?/table//input[@name='ctl00$bc$MFLPasswordPrompt$btnSignIn']", 30000, null, "f127c316-d5e7-4daa-932e-ee537d2476f6");
                _label_invalidloginInfo = new RepoItemInfo(this, "Label_InvalidLogin", "center/table[2]/tbody/tr[2]/?/?/table/tbody/tr[3]/?/?/table//span[@innertext~'^An\\ invalid\\ login\\ or\\ passw']", 30000, null, "0fb65e35-ef9c-4f88-9295-52ec9e80de90");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("07de2267-1342-40f9-971f-366693965382")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("07de2267-1342-40f9-971f-366693965382")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Label_NewApp item.
            /// </summary>
            [RepositoryItem("8b92ef18-cc48-4f08-8537-092cfcd6fc12")]
            public virtual Ranorex.ImgTag Label_NewApp
            {
                get
                {
                    return _label_newappInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Label_NewApp item info.
            /// </summary>
            [RepositoryItemInfo("8b92ef18-cc48-4f08-8537-092cfcd6fc12")]
            public virtual RepoItemInfo Label_NewAppInfo
            {
                get
                {
                    return _label_newappInfo;
                }
            }

            /// <summary>
            /// The ListItem_Vehicle item.
            /// </summary>
            [RepositoryItem("bc08fba5-85ac-4b90-b1ad-e0be997bd8c8")]
            public virtual Ranorex.ATag ListItem_Vehicle
            {
                get
                {
                    return _listitem_vehicleInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ListItem_Vehicle item info.
            /// </summary>
            [RepositoryItemInfo("bc08fba5-85ac-4b90-b1ad-e0be997bd8c8")]
            public virtual RepoItemInfo ListItem_VehicleInfo
            {
                get
                {
                    return _listitem_vehicleInfo;
                }
            }

            /// <summary>
            /// The Editbox_Password item.
            /// </summary>
            [RepositoryItem("f704986e-abbb-4379-8fc3-56d5f4a1067f")]
            public virtual Ranorex.InputTag Editbox_Password
            {
                get
                {
                    return _editbox_passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_Password item info.
            /// </summary>
            [RepositoryItemInfo("f704986e-abbb-4379-8fc3-56d5f4a1067f")]
            public virtual RepoItemInfo Editbox_PasswordInfo
            {
                get
                {
                    return _editbox_passwordInfo;
                }
            }

            /// <summary>
            /// The Button_SignIn item.
            /// </summary>
            [RepositoryItem("f127c316-d5e7-4daa-932e-ee537d2476f6")]
            public virtual Ranorex.InputTag Button_SignIn
            {
                get
                {
                    return _button_signinInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Button_SignIn item info.
            /// </summary>
            [RepositoryItemInfo("f127c316-d5e7-4daa-932e-ee537d2476f6")]
            public virtual RepoItemInfo Button_SignInInfo
            {
                get
                {
                    return _button_signinInfo;
                }
            }

            /// <summary>
            /// The Label_InvalidLogin item.
            /// </summary>
            [RepositoryItem("0fb65e35-ef9c-4f88-9295-52ec9e80de90")]
            public virtual Ranorex.SpanTag Label_InvalidLogin
            {
                get
                {
                    return _label_invalidloginInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Label_InvalidLogin item info.
            /// </summary>
            [RepositoryItemInfo("0fb65e35-ef9c-4f88-9295-52ec9e80de90")]
            public virtual RepoItemInfo Label_InvalidLoginInfo
            {
                get
                {
                    return _label_invalidloginInfo;
                }
            }
        }

        /// <summary>
        /// The VehicleFormFolder folder.
        /// </summary>
        [RepositoryFolder("c0ec1c1e-36dd-4e04-bfd8-67c7352ac018")]
        public partial class VehicleFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _editbox_ssnInfo;
            RepoItemInfo _button_pullcreitandsaveInfo;
            RepoItemInfo _dropdown_purposetypeInfo;
            RepoItemInfo _checkbox_hearaboutorganisationInfo;
            RepoItemInfo _dropdown_directdpositInfo;
            RepoItemInfo _editbox_amountrequestedInfo;
            RepoItemInfo _dropdown_automaticpaymentsInfo;
            RepoItemInfo _img_vehicleappInfo;
            RepoItemInfo _editbox_loantermInfo;
            RepoItemInfo _label_refferedproductsInfo;
            RepoItemInfo _editbox_contactnumberInfo;
            RepoItemInfo _editbox_descriptionInfo;
            RepoItemInfo _checkbox_vehicleloanInfo;
            RepoItemInfo _saforeigncellphonetbphonenumberInfo;
            RepoItemInfo _editbox_extInfo;

            /// <summary>
            /// Creates a new VehicleForm  folder.
            /// </summary>
            public VehicleFormFolder(RepoGenBaseFolder parentFolder) :
                    base("VehicleForm", "", parentFolder, 30000, null, false, "c0ec1c1e-36dd-4e04-bfd8-67c7352ac018", "")
            {
                _editbox_ssnInfo = new RepoItemInfo(this, "Editbox_SSN", ".//input[#'sa_SSN']", 30000, null, "87428001-3325-43ec-957f-3560ceef94db");
                _button_pullcreitandsaveInfo = new RepoItemInfo(this, "Button_PullCreitAndSave", ".//button[#'runcredit_btnSavePullCredit']", 30000, null, "264c4563-a584-45e8-8693-7b1bb383938e");
                _dropdown_purposetypeInfo = new RepoItemInfo(this, "DropDown_PurposeType", ".//select[#'RequestType_RequestType']", 30000, null, "1bb73e5e-f863-4edb-86ee-f2310a820166");
                _checkbox_hearaboutorganisationInfo = new RepoItemInfo(this, "CheckBox_HearAboutOrganisation", ".//table[#'content']//td/table[3]/tbody/tr[1]/td[3]/table/tbody/tr[1]/?/?/input[@name='CQuest$rpt$ctl01$SingleCustomQuestion$chkAnswer$1']", 30000, null, "0ee590c5-c1de-4fce-ad95-7508bff282e7");
                _dropdown_directdpositInfo = new RepoItemInfo(this, "DropDown_DirectDposit", ".//table[#'content']//td/table[3]/tbody/tr[3]/td[3]/select[@name='CQuest$rpt$ctl04$SingleCustomQuestion$drpAnswer']", 30000, null, "8fe8c8a8-c8a4-4f37-8e10-dd1b7d077da3");
                _editbox_amountrequestedInfo = new RepoItemInfo(this, "Editbox_AmountRequested", ".//input[#'AmountRequested']", 30000, null, "06c5b5cf-89f9-4268-af6a-3fba3243c29c");
                _dropdown_automaticpaymentsInfo = new RepoItemInfo(this, "DropDown_AutomaticPayments", ".//table[#'content']//td/table[3]/tbody/tr[2]/td[3]/select[@name='CQuest$rpt$ctl03$SingleCustomQuestion$drpAnswer']", 30000, null, "55a50d22-3c94-4613-b9ae-5e17f172bd85");
                _img_vehicleappInfo = new RepoItemInfo(this, "Img_VehicleApp", ".//form[#'frm']/table//img[@src='https://beta.loanspq.com/Lender/Vehicle/images/vl_section_title.gif']", 30000, null, "6cddc7f5-6161-4ece-b082-caf1cb476d7c");
                _editbox_loantermInfo = new RepoItemInfo(this, "Editbox_LoanTerm", ".//input[#'LoanTerm']", 30000, null, "a62a3faa-f730-4f2f-810f-71b271907b41");
                _label_refferedproductsInfo = new RepoItemInfo(this, "Label_RefferedProducts", ".//div[#'TAB_divReferredProducts']", 30000, null, "6eba4486-c9a3-412e-8375-0ea694a3772d");
                _editbox_contactnumberInfo = new RepoItemInfo(this, "Editbox_ContactNumber", ".//div[#'content']/?/?/table/tbody/tr[3]/?/?/input[@name='ctl00$bc$ContactNumber']", 30000, null, "f5ec995a-9b6e-4184-9392-19e90a7fc505");
                _editbox_descriptionInfo = new RepoItemInfo(this, "Editbox_Description", ".//div[#'content']/?/?/table/tbody/tr[12]/?/?/textarea[@required='False']", 30000, null, "081d1753-f617-4220-9c3b-ce57a85473ec");
                _checkbox_vehicleloanInfo = new RepoItemInfo(this, "Checkbox_VehicleLoan", ".//div[#'content']/?/?/table/tbody/tr[7]/?/?/table/tbody/tr[2]/?/?/input[@name='ctl00$bc$lstApplicableTypes$5']", 30000, null, "fef27086-dd2a-4ef6-83fd-234476c09bd7");
                _saforeigncellphonetbphonenumberInfo = new RepoItemInfo(this, "SaForeignCellPhoneTbPhoneNumber", ".//input[#'sa_ForeignCellPhone_tbPhoneNumber']", 30000, null, "02bf63f1-a49e-4e28-b262-93b876648642");
                _editbox_extInfo = new RepoItemInfo(this, "Editbox_Ext", ".//input[#'sa_WorkPhoneExtension']", 30000, null, "987bb098-86a1-4e88-8921-d928a0acb97c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c0ec1c1e-36dd-4e04-bfd8-67c7352ac018")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c0ec1c1e-36dd-4e04-bfd8-67c7352ac018")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Editbox_SSN item.
            /// </summary>
            [RepositoryItem("87428001-3325-43ec-957f-3560ceef94db")]
            public virtual Ranorex.InputTag Editbox_SSN
            {
                get
                {
                    return _editbox_ssnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_SSN item info.
            /// </summary>
            [RepositoryItemInfo("87428001-3325-43ec-957f-3560ceef94db")]
            public virtual RepoItemInfo Editbox_SSNInfo
            {
                get
                {
                    return _editbox_ssnInfo;
                }
            }

            /// <summary>
            /// The Button_PullCreitAndSave item.
            /// </summary>
            [RepositoryItem("264c4563-a584-45e8-8693-7b1bb383938e")]
            public virtual Ranorex.ButtonTag Button_PullCreitAndSave
            {
                get
                {
                    return _button_pullcreitandsaveInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Button_PullCreitAndSave item info.
            /// </summary>
            [RepositoryItemInfo("264c4563-a584-45e8-8693-7b1bb383938e")]
            public virtual RepoItemInfo Button_PullCreitAndSaveInfo
            {
                get
                {
                    return _button_pullcreitandsaveInfo;
                }
            }

            /// <summary>
            /// The DropDown_PurposeType item.
            /// </summary>
            [RepositoryItem("1bb73e5e-f863-4edb-86ee-f2310a820166")]
            public virtual Ranorex.SelectTag DropDown_PurposeType
            {
                get
                {
                    return _dropdown_purposetypeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DropDown_PurposeType item info.
            /// </summary>
            [RepositoryItemInfo("1bb73e5e-f863-4edb-86ee-f2310a820166")]
            public virtual RepoItemInfo DropDown_PurposeTypeInfo
            {
                get
                {
                    return _dropdown_purposetypeInfo;
                }
            }

            /// <summary>
            /// The CheckBox_HearAboutOrganisation item.
            /// </summary>
            [RepositoryItem("0ee590c5-c1de-4fce-ad95-7508bff282e7")]
            public virtual Ranorex.InputTag CheckBox_HearAboutOrganisation
            {
                get
                {
                    return _checkbox_hearaboutorganisationInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CheckBox_HearAboutOrganisation item info.
            /// </summary>
            [RepositoryItemInfo("0ee590c5-c1de-4fce-ad95-7508bff282e7")]
            public virtual RepoItemInfo CheckBox_HearAboutOrganisationInfo
            {
                get
                {
                    return _checkbox_hearaboutorganisationInfo;
                }
            }

            /// <summary>
            /// The DropDown_DirectDposit item.
            /// </summary>
            [RepositoryItem("8fe8c8a8-c8a4-4f37-8e10-dd1b7d077da3")]
            public virtual Ranorex.SelectTag DropDown_DirectDposit
            {
                get
                {
                    return _dropdown_directdpositInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DropDown_DirectDposit item info.
            /// </summary>
            [RepositoryItemInfo("8fe8c8a8-c8a4-4f37-8e10-dd1b7d077da3")]
            public virtual RepoItemInfo DropDown_DirectDpositInfo
            {
                get
                {
                    return _dropdown_directdpositInfo;
                }
            }

            /// <summary>
            /// The Editbox_AmountRequested item.
            /// </summary>
            [RepositoryItem("06c5b5cf-89f9-4268-af6a-3fba3243c29c")]
            public virtual Ranorex.InputTag Editbox_AmountRequested
            {
                get
                {
                    return _editbox_amountrequestedInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_AmountRequested item info.
            /// </summary>
            [RepositoryItemInfo("06c5b5cf-89f9-4268-af6a-3fba3243c29c")]
            public virtual RepoItemInfo Editbox_AmountRequestedInfo
            {
                get
                {
                    return _editbox_amountrequestedInfo;
                }
            }

            /// <summary>
            /// The DropDown_AutomaticPayments item.
            /// </summary>
            [RepositoryItem("55a50d22-3c94-4613-b9ae-5e17f172bd85")]
            public virtual Ranorex.SelectTag DropDown_AutomaticPayments
            {
                get
                {
                    return _dropdown_automaticpaymentsInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DropDown_AutomaticPayments item info.
            /// </summary>
            [RepositoryItemInfo("55a50d22-3c94-4613-b9ae-5e17f172bd85")]
            public virtual RepoItemInfo DropDown_AutomaticPaymentsInfo
            {
                get
                {
                    return _dropdown_automaticpaymentsInfo;
                }
            }

            /// <summary>
            /// The Img_VehicleApp item.
            /// </summary>
            [RepositoryItem("6cddc7f5-6161-4ece-b082-caf1cb476d7c")]
            public virtual Ranorex.ImgTag Img_VehicleApp
            {
                get
                {
                    return _img_vehicleappInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Img_VehicleApp item info.
            /// </summary>
            [RepositoryItemInfo("6cddc7f5-6161-4ece-b082-caf1cb476d7c")]
            public virtual RepoItemInfo Img_VehicleAppInfo
            {
                get
                {
                    return _img_vehicleappInfo;
                }
            }

            /// <summary>
            /// The Editbox_LoanTerm item.
            /// </summary>
            [RepositoryItem("a62a3faa-f730-4f2f-810f-71b271907b41")]
            public virtual Ranorex.InputTag Editbox_LoanTerm
            {
                get
                {
                    return _editbox_loantermInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_LoanTerm item info.
            /// </summary>
            [RepositoryItemInfo("a62a3faa-f730-4f2f-810f-71b271907b41")]
            public virtual RepoItemInfo Editbox_LoanTermInfo
            {
                get
                {
                    return _editbox_loantermInfo;
                }
            }

            /// <summary>
            /// The Label_RefferedProducts item.
            /// </summary>
            [RepositoryItem("6eba4486-c9a3-412e-8375-0ea694a3772d")]
            public virtual Ranorex.DivTag Label_RefferedProducts
            {
                get
                {
                    return _label_refferedproductsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Label_RefferedProducts item info.
            /// </summary>
            [RepositoryItemInfo("6eba4486-c9a3-412e-8375-0ea694a3772d")]
            public virtual RepoItemInfo Label_RefferedProductsInfo
            {
                get
                {
                    return _label_refferedproductsInfo;
                }
            }

            /// <summary>
            /// The Editbox_ContactNumber item.
            /// </summary>
            [RepositoryItem("f5ec995a-9b6e-4184-9392-19e90a7fc505")]
            public virtual Ranorex.InputTag Editbox_ContactNumber
            {
                get
                {
                    return _editbox_contactnumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_ContactNumber item info.
            /// </summary>
            [RepositoryItemInfo("f5ec995a-9b6e-4184-9392-19e90a7fc505")]
            public virtual RepoItemInfo Editbox_ContactNumberInfo
            {
                get
                {
                    return _editbox_contactnumberInfo;
                }
            }

            /// <summary>
            /// The Editbox_Description item.
            /// </summary>
            [RepositoryItem("081d1753-f617-4220-9c3b-ce57a85473ec")]
            public virtual Ranorex.TextAreaTag Editbox_Description
            {
                get
                {
                    return _editbox_descriptionInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_Description item info.
            /// </summary>
            [RepositoryItemInfo("081d1753-f617-4220-9c3b-ce57a85473ec")]
            public virtual RepoItemInfo Editbox_DescriptionInfo
            {
                get
                {
                    return _editbox_descriptionInfo;
                }
            }

            /// <summary>
            /// The Checkbox_VehicleLoan item.
            /// </summary>
            [RepositoryItem("fef27086-dd2a-4ef6-83fd-234476c09bd7")]
            public virtual Ranorex.InputTag Checkbox_VehicleLoan
            {
                get
                {
                    return _checkbox_vehicleloanInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Checkbox_VehicleLoan item info.
            /// </summary>
            [RepositoryItemInfo("fef27086-dd2a-4ef6-83fd-234476c09bd7")]
            public virtual RepoItemInfo Checkbox_VehicleLoanInfo
            {
                get
                {
                    return _checkbox_vehicleloanInfo;
                }
            }

            /// <summary>
            /// The SaForeignCellPhoneTbPhoneNumber item.
            /// </summary>
            [RepositoryItem("02bf63f1-a49e-4e28-b262-93b876648642")]
            public virtual Ranorex.InputTag SaForeignCellPhoneTbPhoneNumber
            {
                get
                {
                    return _saforeigncellphonetbphonenumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SaForeignCellPhoneTbPhoneNumber item info.
            /// </summary>
            [RepositoryItemInfo("02bf63f1-a49e-4e28-b262-93b876648642")]
            public virtual RepoItemInfo SaForeignCellPhoneTbPhoneNumberInfo
            {
                get
                {
                    return _saforeigncellphonetbphonenumberInfo;
                }
            }

            /// <summary>
            /// The Editbox_Ext item.
            /// </summary>
            [RepositoryItem("987bb098-86a1-4e88-8921-d928a0acb97c")]
            public virtual Ranorex.InputTag Editbox_Ext
            {
                get
                {
                    return _editbox_extInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Editbox_Ext item info.
            /// </summary>
            [RepositoryItemInfo("987bb098-86a1-4e88-8921-d928a0acb97c")]
            public virtual RepoItemInfo Editbox_ExtInfo
            {
                get
                {
                    return _editbox_extInfo;
                }
            }
        }

        /// <summary>
        /// The Window_ChooseFileToUploadAppFolder folder.
        /// </summary>
        [RepositoryFolder("83e0c404-aa31-4728-8c58-47bfb460ce60")]
        public partial class Window_ChooseFileToUploadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _editbox_filenameInfo;
            RepoItemInfo _button_openInfo;

            /// <summary>
            /// Creates a new Window_ChooseFileToUpload  folder.
            /// </summary>
            public Window_ChooseFileToUploadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Window_ChooseFileToUpload", "/form[@title='Choose File to Upload']", parentFolder, 30000, null, true, "83e0c404-aa31-4728-8c58-47bfb460ce60", "")
            {
                _editbox_filenameInfo = new RepoItemInfo(this, "Editbox_FileName", "combobox[@controlid='1148']", 30000, null, "bd2964c0-d55c-4893-87a3-02a45b9f520f");
                _button_openInfo = new RepoItemInfo(this, "Button_Open", "button[@text='&Open']", 30000, null, "ad2bcc8e-63d9-4c87-96c1-82b0e0f697f6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("83e0c404-aa31-4728-8c58-47bfb460ce60")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("83e0c404-aa31-4728-8c58-47bfb460ce60")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Editbox_FileName item.
            /// </summary>
            [RepositoryItem("bd2964c0-d55c-4893-87a3-02a45b9f520f")]
            public virtual Ranorex.ComboBox Editbox_FileName
            {
                get
                {
                    return _editbox_filenameInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Editbox_FileName item info.
            /// </summary>
            [RepositoryItemInfo("bd2964c0-d55c-4893-87a3-02a45b9f520f")]
            public virtual RepoItemInfo Editbox_FileNameInfo
            {
                get
                {
                    return _editbox_filenameInfo;
                }
            }

            /// <summary>
            /// The Button_Open item.
            /// </summary>
            [RepositoryItem("ad2bcc8e-63d9-4c87-96c1-82b0e0f697f6")]
            public virtual Ranorex.Button Button_Open
            {
                get
                {
                    return _button_openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button_Open item info.
            /// </summary>
            [RepositoryItemInfo("ad2bcc8e-63d9-4c87-96c1-82b0e0f697f6")]
            public virtual RepoItemInfo Button_OpenInfo
            {
                get
                {
                    return _button_openInfo;
                }
            }
        }

        /// <summary>
        /// The MessageFromWebpageAppFolder folder.
        /// </summary>
        [RepositoryFolder("a5d1fad4-2c47-4ad2-8b4d-304eb67d49aa")]
        public partial class MessageFromWebpageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _popup_selectapplicabletypeInfo;
            RepoItemInfo _button_okInfo;
            RepoItemInfo _label_requestsubmittedsuccessfullyInfo;
            RepoItemInfo _label_wouldyouliketoimportmemberdataInfo;

            /// <summary>
            /// Creates a new MessageFromWebpage  folder.
            /// </summary>
            public MessageFromWebpageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MessageFromWebpage", "/form[@title='Message from webpage']", parentFolder, 30000, null, true, "a5d1fad4-2c47-4ad2-8b4d-304eb67d49aa", "")
            {
                _popup_selectapplicabletypeInfo = new RepoItemInfo(this, "PopUp_SelectApplicableType", "text[@controlid='65535' and @text='Please select applicable type(s) for new document.']", 30000, null, "71a4faa3-9bd3-4aa0-b542-a487b0835c61");
                _button_okInfo = new RepoItemInfo(this, "Button_OK", "button[@text='OK']", 30000, null, "7320a05a-7f4f-4a2d-9cdc-f6235f4ecd31");
                _label_requestsubmittedsuccessfullyInfo = new RepoItemInfo(this, "Label_RequestSubmittedSuccessfully", "text[@text='Your request has been successfully submitted.']", 30000, null, "c90fb797-fa7f-4c06-8e3a-0d4aa1b5d142");
                _label_wouldyouliketoimportmemberdataInfo = new RepoItemInfo(this, "Label_WouldYouLikeToImportMemberData", "text[@text='Would you like to import member data and override any existing values you may have entered?']", 30000, null, "306657c3-cd14-4d24-b6dc-6a7c516494b5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a5d1fad4-2c47-4ad2-8b4d-304eb67d49aa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a5d1fad4-2c47-4ad2-8b4d-304eb67d49aa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PopUp_SelectApplicableType item.
            /// </summary>
            [RepositoryItem("71a4faa3-9bd3-4aa0-b542-a487b0835c61")]
            public virtual Ranorex.Text PopUp_SelectApplicableType
            {
                get
                {
                    return _popup_selectapplicabletypeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PopUp_SelectApplicableType item info.
            /// </summary>
            [RepositoryItemInfo("71a4faa3-9bd3-4aa0-b542-a487b0835c61")]
            public virtual RepoItemInfo PopUp_SelectApplicableTypeInfo
            {
                get
                {
                    return _popup_selectapplicabletypeInfo;
                }
            }

            /// <summary>
            /// The Button_OK item.
            /// </summary>
            [RepositoryItem("7320a05a-7f4f-4a2d-9cdc-f6235f4ecd31")]
            public virtual Ranorex.Button Button_OK
            {
                get
                {
                    return _button_okInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button_OK item info.
            /// </summary>
            [RepositoryItemInfo("7320a05a-7f4f-4a2d-9cdc-f6235f4ecd31")]
            public virtual RepoItemInfo Button_OKInfo
            {
                get
                {
                    return _button_okInfo;
                }
            }

            /// <summary>
            /// The Label_RequestSubmittedSuccessfully item.
            /// </summary>
            [RepositoryItem("c90fb797-fa7f-4c06-8e3a-0d4aa1b5d142")]
            public virtual Ranorex.Text Label_RequestSubmittedSuccessfully
            {
                get
                {
                    return _label_requestsubmittedsuccessfullyInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Label_RequestSubmittedSuccessfully item info.
            /// </summary>
            [RepositoryItemInfo("c90fb797-fa7f-4c06-8e3a-0d4aa1b5d142")]
            public virtual RepoItemInfo Label_RequestSubmittedSuccessfullyInfo
            {
                get
                {
                    return _label_requestsubmittedsuccessfullyInfo;
                }
            }

            /// <summary>
            /// The Label_WouldYouLikeToImportMemberData item.
            /// </summary>
            [RepositoryItem("306657c3-cd14-4d24-b6dc-6a7c516494b5")]
            public virtual Ranorex.Text Label_WouldYouLikeToImportMemberData
            {
                get
                {
                    return _label_wouldyouliketoimportmemberdataInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Label_WouldYouLikeToImportMemberData item info.
            /// </summary>
            [RepositoryItemInfo("306657c3-cd14-4d24-b6dc-6a7c516494b5")]
            public virtual RepoItemInfo Label_WouldYouLikeToImportMemberDataInfo
            {
                get
                {
                    return _label_wouldyouliketoimportmemberdataInfo;
                }
            }
        }

        /// <summary>
        /// The DocumentSupportRequestInternetExplAppFolder folder.
        /// </summary>
        [RepositoryFolder("d02b9c9c-b226-4ae5-b0e6-b4b04504e18d")]
        public partial class DocumentSupportRequestInternetExplAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new DocumentSupportRequestInternetExpl  folder.
            /// </summary>
            public DocumentSupportRequestInternetExplAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DocumentSupportRequestInternetExpl", "/form[@title~'^Document\\ Support\\ Request\\ ']", parentFolder, 30000, null, true, "d02b9c9c-b226-4ae5-b0e6-b4b04504e18d", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d02b9c9c-b226-4ae5-b0e6-b4b04504e18d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d02b9c9c-b226-4ae5-b0e6-b4b04504e18d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
